default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: 'yhkygake'
  password: '9C0dPdiylEaRA0DNI9KYUstNlpo60G2R'
  url: 'postgres://yhkygake:9C0dPdiylEaRA0DNI9KYUstNlpo60G2R@hansken.db.elephantsql.com/yhkygake'

development:
  <<: *default
  database: dev-bd

test:
  <<: *default
  database: dev-test

production:
  <<: *default
  database: dev-prod
  username: ""
  password: ""